name: app_store
description: App Store
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.15+1
  flutter_riverpod: ^2.3.6
  gtk: ^2.1.0
  handy_window: ^0.3.1
  shimmer: ^3.0.0
  snapd: ^0.4.9
  ubuntu_localizations: ^0.3.3
  ubuntu_service: ^0.2.2
  ubuntu_test:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_test
      ref: d8490a876e0e499220930f0d7e8b4a20ae623629
  yaru: ^0.9.0
  yaru_icons: ^1.0.4
  yaru_widgets: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.5
  fake_async: ^1.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.4.2

dependency_overrides:
  yaru_widgets:
    git:
      url: https://github.com/ubuntu/yaru_widgets.dart
      ref: dc9af5c03d5606ecd0ff2d2e332d71295b1b0864

flutter:
  uses-material-design: true
  generate: true
