name: app_store
description: App Store
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  handy_window: ^0.3.1
  snapd: ^0.4.9
  ubuntu_service: ^0.2.2
  yaru: ^0.9.0
  yaru_icons: ^1.0.4
  yaru_widgets: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.5
  fake_async: ^1.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.4.2

dependency_overrides:
  yaru_widgets:
    git:
      url: https://github.com/ubuntu/yaru_widgets.dart
      ref: navigation

flutter:
  uses-material-design: true
  generate: true
