name: snap-store
summary: Snap Store
description: Snap Store
confinement: strict
base: core22
grade: stable
version: git

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-tag: 3.10.5
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      mkdir -p $CRAFT_PART_INSTALL/usr/libexec
      cp -r $CRAFT_PART_SRC $CRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $CRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $CRAFT_PART_INSTALL/usr/bin/flutter
      $CRAFT_PART_INSTALL/usr/bin/flutter doctor
    build-packages:
      - clang
      - cmake
      - curl
      - libgtk-3-dev
      - ninja-build
      - unzip
      - xz-utils
      - zip
    override-prime: ''

  snap-store:
    after: [flutter-git]
    source: .
    plugin: nil
    override-build: |
      set -eux
      flutter pub get
      flutter build linux --release -v
      mkdir -p $CRAFT_PART_INSTALL/bin/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/bin/

apps:
  snap-store:
    command: bin/snap-store
    desktop: bin/data/flutter_assets/assets/snap-store.desktop
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-launch
      - network
      - snapd-control

slots:
  dbus-name:
    interface: dbus
    bus: session
    name: io.snapcraft.Store
